version: "3.8"

services:
  web:
    build: ./web
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

