version: '3.8'

networks:
  my_custom_network:  # Define a custom network

services:
  web:
    image: flask-app
    depends_on:
      - db
    networks:
      my_custom_network: {}  # ✅ Correct mapping syntax

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      my_custom_network: {}  # ✅ Correct mapping syntax

volumes:
  mysql_data:

