version: "3.8"
services:
  db:
    image: mysql:8.0
    deploy:
      replicas: 1
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

